const peacebondTemplates = [
  {
    category: "theft_livestock",
    categoryLabel: "livestock theft",
    focus: "restitution, household repair, and mediated reconciliation",
    keywords: [
      "theft",
      "stole",
      "stolen",
      "livestock",
      "cattle",
      "goat",
      "goats",
      "sheep",
      "mifugo",
      "ng'ombe",
      "mbuzi",
      "betail",
      "chevre",
      "gado",
      "cabra",
      "سرقة",
      "مواشي",
      "ماعز",
    ],
    repairActions: {
      low: [
        "Offer a mediated apology to the affected household and name the item or animal taken.",
        "Return the item or agree on a small restitution contribution witnessed by the mediator.",
        "Complete one short support task chosen by the affected household, such as cleaning or carrying water.",
      ],
      moderate: [
        "Agree on a restitution plan with the affected household and mediator.",
        "Complete supervised community repair work connected to the harm caused.",
        "Attend a peace circle with elders and affected family members to confirm the repair agreement.",
      ],
      high: [
        "Give a formal accountability testimony before mediators, elders, and affected household representatives.",
        "Complete an extended supervised restitution plan that replaces livestock value through labor or agreed installments.",
        "Mentor a younger community member on lawful livelihood choices while completing weekly mediator check-ins.",
      ],
    },
    ritual: "A restitution gathering where the affected household receives the repair commitment with trusted witnesses.",
  },
  {
    category: "destruction_property",
    categoryLabel: "property damage",
    focus: "repair work, material replacement, and restored community safety",
    keywords: [
      "destruction",
      "destroyed",
      "damaged",
      "burned",
      "broke",
      "broken",
      "vandalized",
      "property",
      "haribu",
      "uharibifu",
      "mali",
      "endommage",
      "propriete",
      "dano",
      "danificado",
      "propriedade",
      "إتلاف",
      "ضرر",
      "ممتلكات",
    ],
    repairActions: {
      low: [
        "Apologize to the owner in a mediated meeting and identify the specific damage caused.",
        "Provide a small replacement item or repair material agreed with the mediator.",
        "Complete a short supervised repair task at the damaged site.",
      ],
      moderate: [
        "Join the mediator and owner to agree on a practical repair schedule.",
        "Complete supervised repair labor until the damaged property is usable again.",
        "Attend a community check-in where the repaired property and future safety commitments are acknowledged.",
      ],
      high: [
        "Give a formal account of the damage caused and accept a written repair agreement.",
        "Complete extended supervised rebuilding work with weekly mediator verification.",
        "Support a community safety activity that prevents future damage, such as restoring shared fencing or lighting.",
      ],
    },
    ritual: "A rebuilding day that closes with community acknowledgment of restored safety and shared responsibility.",
  },
  {
    category: "resource_theft",
    categoryLabel: "resource theft",
    focus: "restitution, shared resource access, and mediated accountability",
    keywords: [
      "resource",
      "resources",
      "water",
      "relief item",
      "relief items",
      "ration",
      "rations",
      "tools",
      "equipment",
      "nets",
      "seeds",
      "fuel",
      "stole",
      "stolen",
      "wizi wa rasilimali",
      "ressource",
      "recursos",
      "مورد",
      "موارد",
    ],
    repairActions: {
      low: [
        "Name the shared resource harm in mediation and identify affected households.",
        "Return the resource or agree on a small restitution step witnessed by the mediator.",
        "Complete one practical task that helps restore shared access to the resource.",
      ],
      moderate: [
        "Create a mediated restitution plan focused on shared resource access and trust.",
        "Complete supervised work that restores or replaces the affected resource.",
        "Attend a community check-in where access commitments and future safeguards are confirmed.",
      ],
      high: [
        "Give a formal accountability statement before mediators and affected resource users.",
        "Complete an extended restitution plan with documented check-ins and supervised repair work.",
        "Support a community resource access activity that reduces future harm and strengthens safe return.",
      ],
    },
    ritual:
      "A resource repair meeting where affected households confirm restitution and renewed access commitments.",
  },
  {
    category: "livelihood_disruption",
    categoryLabel: "livelihood disruption",
    focus: "restoring tools, work access, and community trust around daily livelihood",
    keywords: [
      "livelihood",
      "income",
      "work access",
      "blocked work",
      "market access",
      "trade disruption",
      "fishing work",
      "farm work",
      "riziki",
      "moyens de subsistance",
      "meios de vida",
      "سبل العيش",
    ],
    repairActions: {
      low: [
        "Meet with a mediator to identify how livelihood access was disrupted.",
        "Offer a respectful apology and one agreed step toward restored work access.",
        "Complete a short practical task that supports the affected livelihood.",
      ],
      moderate: [
        "Create a mediated plan for restoring tools, work access, or trading trust.",
        "Complete supervised repair or service work tied to the affected livelihood.",
        "Attend a livelihood restoration circle where affected people confirm next steps.",
      ],
      high: [
        "Give a formal accountability statement about the livelihood disruption and its effects.",
        "Complete an extended supervised restoration plan with mediator verification.",
        "Support a reintegration activity that strengthens safe access to work for affected households.",
      ],
    },
    ritual:
      "A livelihood restoration circle where work access, repair tasks, and support are acknowledged.",
  },
  {
    category: "displacement_impact",
    categoryLabel: "community displacement impact",
    focus: "safe return, shared shelter or service access, and careful community mediation",
    keywords: [
      "displacement",
      "displaced",
      "camp",
      "temporary camp",
      "relocation",
      "relocated",
      "shelter",
      "registration",
      "aid access",
      "refugee",
      "wakimbizi",
      "deplacement",
      "refugies",
      "deslocamento",
      "refugiados",
      "نزوح",
      "لاجئ",
      "مخيم",
    ],
    repairActions: {
      low: [
        "Meet with a mediator to name the displacement-related harm without exposing vulnerable households.",
        "Agree on one safe repair step that supports shared shelter, service access, or respectful return.",
        "Complete a practical support task witnessed by a trusted community representative.",
      ],
      moderate: [
        "Create a careful repair agreement focused on safe access, dignity, and reduced tension.",
        "Complete supervised community support work connected to shelter, services, or return.",
        "Attend a small reconciliation meeting where safety and dignity commitments are confirmed.",
      ],
      high: [
        "Give a formal accountability statement before mediators and trusted protection-sensitive representatives.",
        "Complete an extended supervised repair plan that avoids exposure and supports safe community access.",
        "Support a displacement-aware reintegration activity that strengthens peaceful return and service access.",
      ],
    },
    ritual:
      "A careful welcome meeting where repair commitments are witnessed without exposing vulnerable households.",
  },
  {
    category: "militia_armed",
    categoryLabel: "armed group involvement",
    focus: "accountability testimony, supervised service, and peaceful role formation",
    keywords: [
      "militia",
      "armed",
      "fighter",
      "weapon",
      "combatant",
      "rebel",
      "raid",
      "gun",
      "wanamgambo",
      "silaha",
      "milice",
      "arme",
      "combatant",
      "milicia",
      "armado",
      "arma",
      "مسلحة",
      "سلاح",
      "مقاتل",
    ],
    repairActions: {
      low: [
        "Meet with a mediator to describe the role played without glorifying violence.",
        "Apologize to affected representatives for fear caused by armed presence or association.",
        "Complete one supervised community service task that supports peaceful return.",
      ],
      moderate: [
        "Give a guided testimony that acknowledges harm and explains the commitment to nonviolence.",
        "Complete supervised service work chosen by a community mediation group.",
        "Attend a peace circle focused on safety commitments and practical reintegration support.",
      ],
      high: [
        "Give formal accountability testimony before mediators, elders, and community safety representatives.",
        "Complete an extended supervised service plan with documented weekly attendance.",
        "Mentor at-risk youth toward nonviolent choices with mediator oversight.",
      ],
    },
    ritual: "A community witnessing circle where testimony is heard and a peaceful role is affirmed.",
  },
  {
    category: "violence_fighting",
    categoryLabel: "violence or fighting",
    focus: "apology, safety commitments, and peace circle repair",
    keywords: [
      "violence",
      "violent",
      "fight",
      "fighting",
      "assault",
      "hit",
      "injured",
      "beating",
      "attack",
      "vurugu",
      "mapigano",
      "violence",
      "bagarre",
      "violencia",
      "briga",
      "عنف",
      "شجار",
      "اعتداء",
    ],
    repairActions: {
      low: [
        "Offer a mediated apology if the harmed person agrees to receive it.",
        "Join a short mediation meeting to agree on respectful future contact.",
        "Complete one practical support task selected by the mediator to repair community trust.",
      ],
      moderate: [
        "Attend a peace circle focused on responsibility, safety, and future contact boundaries.",
        "Complete a supervised repair task chosen by the affected person or mediation group.",
        "Write or speak a safety commitment that is witnessed by the mediator and community elders.",
      ],
      high: [
        "Give a formal accountability statement that names the harm and accepts safety conditions.",
        "Complete extended supervised community service focused on restoring public safety.",
        "Attend follow-up reconciliation sessions with mediators before any public acknowledgment ritual.",
      ],
    },
    ritual: "A peace circle where safety commitments and repair actions are spoken aloud with care.",
  },
  {
    category: "verbal_threats",
    categoryLabel: "verbal threats",
    focus: "apology, mediation, and respectful communication",
    keywords: [
      "threat",
      "threats",
      "verbal",
      "insult",
      "intimidated",
      "harassed",
      "abuse",
      "vitisho",
      "matusi",
      "menace",
      "insulte",
      "ameaca",
      "verbal",
      "تهديد",
      "إهانة",
    ],
    repairActions: {
      low: [
        "Offer a clear mediated apology for the words used and the fear they caused.",
        "Agree on a respectful contact boundary with the mediator present.",
        "Complete a short reflection statement on nonviolent speech and community dignity.",
      ],
      moderate: [
        "Attend a mediation session with the affected person or representative if they consent.",
        "Participate in a community dialogue on respectful speech and de-escalation.",
        "Complete a follow-up check-in with the mediator to confirm the agreement is being honored.",
      ],
      high: [
        "Give a formal acknowledgment of the threats and agree to a written non-intimidation plan.",
        "Complete multiple mediator check-ins focused on safe communication and emotional regulation.",
        "Support a community dialogue activity that helps prevent intimidation and verbal harm.",
      ],
    },
    ritual: "A mediation meeting where harmful words are replaced with public commitments to respect.",
  },
  {
    category: "land_dispute",
    categoryLabel: "land dispute",
    focus: "boundary mediation, dialogue, and shared agreement",
    keywords: [
      "land",
      "boundary",
      "farm",
      "field",
      "plot",
      "dispute",
      "property",
      "border",
      "ardhi",
      "mpaka",
      "shamba",
      "terre",
      "limite",
      "foncier",
      "terra",
      "limite",
      "ارض",
      "حدود",
      "نزاع",
    ],
    repairActions: {
      low: [
        "Attend a short boundary mediation meeting with trusted local witnesses.",
        "Listen to the affected household's account without interruption.",
        "Sign or verbally confirm a simple temporary boundary agreement.",
      ],
      moderate: [
        "Participate in a boundary walk with mediators, elders, and affected household representatives.",
        "Help mark agreed boundary points with simple materials provided through mediation.",
        "Attend a dialogue session to document future land-use commitments.",
      ],
      high: [
        "Give a formal statement accepting the mediation process and pausing disputed land use.",
        "Complete supervised work to restore damaged boundary markers or shared access paths.",
        "Attend extended dialogue sessions until a witnessed land-use agreement is documented.",
      ],
    },
    ritual: "A boundary walk where agreed markers are recognized by both families or groups.",
  },
];

const defaultTemplate = {
  category: "general_harm",
  categoryLabel: "general community harm",
  focus: "listening, practical repair, and mediated return",
  keywords: [],
  repairActions: {
    low: [
      "Meet with a mediator to name the harm and identify who was affected.",
      "Offer a respectful apology or commitment if the affected person agrees to receive it.",
      "Complete one short practical repair task chosen through community dialogue.",
    ],
    moderate: [
      "Create a repair agreement with the mediator and affected representatives.",
      "Complete supervised service that responds to the harm and supports community trust.",
      "Attend a peace circle to review the repair work and confirm next steps.",
    ],
    high: [
      "Give a formal accountability statement before mediators and trusted community representatives.",
      "Complete an extended supervised service plan with documented check-ins.",
      "Participate in follow-up reconciliation sessions before a completion ritual is held.",
    ],
  },
  ritual: "A quiet reconciliation meeting where repair commitments are witnessed.",
};

module.exports = {
  defaultTemplate,
  peacebondTemplates,
};
